### PR TITLE
Spigot-ping for 1.17

### PR DESCRIPTION
**Pull request by prodesert22**
Bug fix in getping
bug
and change sound NOTE_PLING for BLOCK_NOTE_BLOCK_PLING

### CODE REVIEW

**Comment by xDefcon** [comment]
I'll merge the PR and release the update tomorrow. Thanks for the contribution.

**Comment by xDefcon** [comment]
https://www.spigotmc.org/resources/spigotping-added-in-tablist-ping.24419/update?update=407540

**Comment by DrakeM2C** [comment]
Can you update these plugins to support Minecraft Java 1.21x for example Minecraft 1.21.5

**Comment by xDefcon** [comment]
@DrakeM2C I'll take care of updating the plugin in the coming days, thank you

**Pull request merged**
